import React, { useEffect, useMemo, useState } from 'react';
import { createPortal } from 'react-dom';
import { useNavigate, useParams } from 'react-router-dom';
import { ArrowLeft, Check, ChevronDown, FileText, Plus, Trash2, Upload, X } from 'lucide-react';
import DashboardShell from '../components/dashboard/DashboardShell';
import { apiService, getApiErrorMessage, uploadMediaFiles } from '../services/api';

export const SERVICE_MASTER = ['CASE REPRESENTATION','CAT-1-EOL CREDIT','CAT-1-RECYCLING CREDIT','CAT-2-EOL CREDIT','CAT-2-RECYCLING CREDIT','CAT-3-EOL CREDIT','CAT-3-RECYCLING CREDIT','CATEGORY 1','CATEGORY 2','CATEGORY 3','CGWA NOC FRESH APPLICATION','CONSULTANCY FEE','CPCB NOTICE REPLY FEES','CTE & CTO NEW REGISTRATION','CTE – CONSENT TO ESTABLISH','CTO – CONSENT TO OPERATE','CTO – RENEWAL','E-WASTE CREDIT','ENVIRONMENT STATEMENT FORM V SUBMISSION','EPR CREDIT RE','EPR CREDIT REVENUE SHARING','EPR ETP PORTAL HANDLING CHARGES','EPR LOGIN SURRENDER','GOVT. REPRESENTATION CHARGES','KAVACH AUDIT','MATERIAL WASTE DISPOSAL CONSULTANCY','PLANT AUDIT','PORTAL HEALTH REPORT CONSULTANCY','SAP INTEGRATION SUPPORT','UREP ASSESSMENT AND CONSULTING'];

const blankRow = (year = '', service = []) => ({ fyYear: year, poNumber: '', file: null, service: [...service] });
const userFromStorage = () => { try { return JSON.parse(localStorage.getItem('user') || 'null'); } catch { return null; } };
const yearsFrom = (first) => {
  const match = String(first || '').match(/^(\d{4})/); const start = match ? Number(match[1]) : new Date().getFullYear() - 2;
  const now = new Date(); const last = now.getMonth() >= 3 ? now.getFullYear() : now.getFullYear() - 1;
  return Array.from({ length: Math.max(1, last - start + 1) }, (_, index) => `${start + index}-${String(start + index + 1).slice(-2)}`);
};

export default function ClientAnnualReturns() {
  const { clientKey } = useParams(); const navigate = useNavigate();
  const [client, setClient] = useState(null); const [annualReturn, setAnnualReturn] = useState({ filings: {} });
  const [modalOpen, setModalOpen] = useState(true); const [toast, setToast] = useState('');
  const years = useMemo(() => yearsFrom(client?.data?.basic?.firstAnnualReturnYear || client?.firstAnnualReturnYear), [client]);
  const isUnlocked = (year) => {
    const confirmations = Object.values(annualReturn?.filings || {}).map((filing) => filing?.draft?.purchaseOrderConfirmation).filter(Boolean);
    return confirmations.some((po) => po.mode === 'no' && po.confirmed && ((po.approvalFiles || []).length || po.approvalNote)) || confirmations.some((po) => po.mode === 'yes' && po.confirmed && (po.rows || []).some((row) => row.fyYear === year));
  };
  async function load() {
    try { const { data } = await apiService.clients.getAnnualReturn(clientKey); setClient(data.client); setAnnualReturn(data.annualReturn || { filings: {} });
      const missing = yearsFrom(data.client?.data?.basic?.firstAnnualReturnYear || data.client?.firstAnnualReturnYear).filter((year) => !Object.values(data.annualReturn?.filings || {}).some((filing) => { const po = filing?.draft?.purchaseOrderConfirmation; return po?.mode === 'no' && po.confirmed || po?.rows?.some((row) => row.fyYear === year); }));
      if (missing.length) setToast(`You didn't fill Annual Return ${missing.join(', ')}. Complete PO details to unlock these years.`);
    } catch (error) { setToast(getApiErrorMessage(error, 'Unable to load annual returns')); }
  }
  useEffect(() => { load(); }, [clientKey]);
  return <DashboardShell currentUser={userFromStorage()} onLogout={() => navigate('/')}>
    {toast && <div className="fixed right-5 top-24 z-[120] max-w-md rounded-2xl border border-red-200 bg-red-50 p-4 font-bold text-red-700 shadow-xl">{toast}</div>}
    <main className="px-4 py-7 sm:px-7"><div className="mx-auto max-w-[1480px]">
      <button onClick={() => navigate('/sales/client-master')} className="inline-flex items-center gap-2 rounded-xl border border-teal-200 bg-white px-4 py-3 font-black text-teal-800"><ArrowLeft className="h-4 w-4" /> Back to Client Master</button>
      <section className="mt-5 rounded-[28px] border border-teal-100 bg-gradient-to-r from-teal-50 via-white to-amber-50 p-6 shadow-sm"><p className="text-xs font-black uppercase tracking-widest text-teal-700">Annual Return History</p><h1 className="mt-2 text-3xl font-black text-slate-950">{client?.data?.basic?.clientLegalName || 'Client'}</h1><p className="mt-1 font-bold text-slate-500">Unique ID: {client?.clientIdentity?.uniqueId || client?.clientIdentity?.key || clientKey}</p><button onClick={() => setModalOpen(true)} className="mt-5 rounded-xl bg-teal-700 px-5 py-3 font-black text-white">Purchase Order Confirmation</button></section>
      <div className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{years.map((year) => { const unlocked = isUnlocked(year); return <button key={year} onClick={() => unlocked ? navigate(`/sales/client-data-processing/${encodeURIComponent(clientKey)}/${year}`) : (setToast(`You didn't fill Annual Return ${years.filter((item) => !isUnlocked(item)).join(', ')}. Complete PO details to unlock these years.`), setModalOpen(true))} className={`rounded-2xl border p-6 text-left shadow-sm ${unlocked ? 'border-teal-200 bg-white hover:bg-teal-50' : 'border-red-200 bg-red-50'}`}><FileText className={unlocked ? 'text-teal-700' : 'text-red-500'} /><h2 className="mt-4 text-xl font-black text-slate-900">{year}</h2><p className={`mt-2 font-bold ${unlocked ? 'text-teal-700' : 'text-red-600'}`}>{unlocked ? 'Open annual return' : 'Frozen — PO details pending'}</p></button>; })}</div>
    </div></main>
    {modalOpen && <PurchaseOrderModal years={years} annualReturn={annualReturn} clientKey={clientKey} onClose={() => setModalOpen(false)} onSaved={async () => { await load(); setModalOpen(false); }} onError={setToast} />}
  </DashboardShell>;
}

function PurchaseOrderModal({ years, annualReturn, clientKey, onClose, onSaved, onError }) {
  const prior = Object.values(annualReturn?.filings || {}).map((item) => item?.draft?.purchaseOrderConfirmation).find(Boolean);
  const [mode, setMode] = useState(prior?.mode || null); const [rows, setRows] = useState(prior?.rows?.length ? prior.rows : [blankRow(years[0])]);
  const [approvalFiles, setApprovalFiles] = useState(prior?.approvalFiles || []); const [approvalNote, setApprovalNote] = useState(prior?.approvalNote || ''); const [saving, setSaving] = useState(false);
  useEffect(() => { const old = document.body.style.overflow; document.body.style.overflow = 'hidden'; return () => { document.body.style.overflow = old; }; }, []);
  const readFiles = (files, section = 'annual-return-documents') => uploadMediaFiles(files, section);
  function addYear() { const next = years.find((year) => !rows.some((row) => row.fyYear === year)) || ''; setRows((current) => [...current, blankRow(next, current.at(-1)?.service || [])]); }
  async function uploadPo(index, files) { try { const [file] = await readFiles(files, 'annual-return-purchase-orders'); setRows((all) => all.map((item, i) => i === index ? { ...item, file } : item)); } catch (error) { onError(getApiErrorMessage(error, error.message || 'Cloudinary upload failed')); } }
  async function save() {
    if (!mode) return onError('Please select Yes or No for PO Received.');
    if (mode === 'yes') { const duplicate = new Set(rows.map((row) => row.fyYear)).size !== rows.length; if (duplicate) return onError('Duplicate FY years are not allowed.'); if (rows.some((row) => !row.fyYear || !row.poNumber.trim() || !row.file?.url || !row.service.length)) return onError('Every PO row requires FY Year, PO Number, PO Upload, and at least one Service.'); }
    if (mode === 'no' && !approvalFiles.length && !approvalNote.trim()) return onError('Upload special approval proof or enter the approval email/note.');
    setSaving(true); try { await apiService.clients.saveAnnualReturn(clientKey, { annualYear: rows[0]?.fyYear || years[0], activeTab: 'basic', activeSection: 'Purchase Order Confirmation', status: 'draft', draft: { purchaseOrderConfirmation: mode === 'yes' ? { mode, confirmed: true, rows } : { mode, confirmed: true, approvalFiles, approvalNote } } }); await onSaved(); } catch (error) { onError(getApiErrorMessage(error, 'Unable to save PO confirmation')); } finally { setSaving(false); }
  }
  return createPortal(<div className="fixed inset-0 z-[200] flex items-center justify-center bg-slate-950/55 p-3 sm:p-6"><section className="flex max-h-[94vh] w-full max-w-[1480px] flex-col overflow-hidden rounded-[28px] border border-teal-100 bg-[#fffdf7] shadow-2xl">
    <header className="flex shrink-0 items-center justify-between border-b border-teal-100 bg-gradient-to-r from-teal-50 to-amber-50 px-6 py-5"><div><p className="text-xs font-black uppercase tracking-widest text-teal-700">Annual Return</p><h2 className="text-2xl font-black text-slate-950">Purchase Order Confirmation</h2></div><button onClick={onClose} className="rounded-xl p-2 hover:bg-white"><X /></button></header>
    <div className="min-h-0 flex-1 overflow-y-auto p-5 sm:p-7">
      {!mode && <div className="mb-6 rounded-2xl border border-cyan-200 bg-cyan-50 p-5"><h3 className="font-black text-teal-900">Select PO availability</h3><p className="mt-1 font-semibold text-slate-600">Choose Yes to add financial-year purchase orders, or No to provide special approval proof.</p></div>}
      <p className="font-black text-slate-800">PO Received</p><div className="mt-3 flex gap-3">{['yes','no'].map((choice) => <button key={choice} onClick={() => setMode(choice)} className={`flex min-w-32 items-center justify-center gap-2 rounded-xl border px-5 py-3 font-black capitalize ${mode === choice ? 'border-teal-600 bg-teal-100 text-teal-900 ring-4 ring-teal-100 shadow-md' : 'border-slate-200 bg-white text-slate-600'}`}>{mode === choice && <Check className="h-4 w-4" />}{choice}</button>)}</div>
      {mode === 'yes' && <div className="mt-7"><div className="mb-4 flex flex-wrap items-center justify-between gap-3"><h3 className="text-xl font-black">Number of PO years: {rows.length}</h3><div className="flex gap-2"><button onClick={addYear} className="rounded-xl bg-teal-700 px-4 py-2 font-black text-white"><Plus className="mr-1 inline h-4" /> Add Next Year</button><button disabled={rows.length <= 1} onClick={() => setRows((current) => current.slice(0, -1))} className="rounded-xl border border-red-200 bg-white px-4 py-2 font-black text-red-600 disabled:opacity-40">Remove Last Year</button></div></div><div className="overflow-x-auto rounded-2xl border border-teal-100 bg-white"><table className="min-w-[1180px] w-full text-left"><thead className="border-b-2 border-teal-200 bg-gradient-to-r from-teal-50 via-emerald-50 to-cyan-50 text-teal-900"><tr>{['Sr. No','FY Year','PO Number','PO Upload','Services'].map((head) => <th key={head} className="p-5 font-black last:min-w-[420px]">{head}</th>)}</tr></thead><tbody>{rows.map((row, index) => <tr key={index} className="border-b border-slate-100 hover:bg-teal-50/40"><td className="p-5 font-black">{index + 1}</td><td className="p-5"><select className="form-input" value={row.fyYear} onChange={(e) => setRows((all) => all.map((item, i) => i === index ? { ...item, fyYear: e.target.value } : item))}><option value="">Select FY</option>{years.map((year) => <option key={year}>{year}</option>)}</select></td><td className="p-5"><input className="form-input" value={row.poNumber} onChange={(e) => setRows((all) => all.map((item, i) => i === index ? { ...item, poNumber: e.target.value } : item))} /></td><td className="p-5"><label className="inline-flex cursor-pointer items-center gap-2 rounded-xl border border-teal-200 px-4 py-3 font-black text-teal-700"><Upload className="h-4" />{row.file?.name || 'Upload PO'}<input type="file" className="sr-only" accept=".pdf,.doc,.docx,image/*" onChange={(e) => uploadPo(index, e.target.files)} /></label></td><td className="p-5"><ServiceMultiSelect value={row.service} onChange={(service) => setRows((all) => all.map((item, i) => i === index ? { ...item, service } : item))} /></td></tr>)}</tbody></table></div></div>}
      {mode === 'no' && <div className="mt-7 rounded-2xl border border-teal-100 bg-white p-6"><h3 className="text-xl font-black">Please Provide Special Approval</h3><label className="mt-5 inline-flex cursor-pointer items-center gap-2 rounded-xl border border-teal-200 px-5 py-3 font-black text-teal-700"><Upload className="h-4" /> Upload Images / Email<input multiple type="file" accept="image/*,.pdf,.eml,.msg" className="sr-only" onChange={async (e) => { try { const files = await readFiles(e.target.files, 'annual-return-approvals'); setApprovalFiles((old) => [...old, ...files]); } catch (error) { onError(getApiErrorMessage(error, error.message || 'Cloudinary upload failed')); } }} /></label><div className="mt-3 flex flex-wrap gap-2">{approvalFiles.map((file, index) => <span key={index} className="rounded-full bg-teal-50 px-3 py-2 text-sm font-bold text-teal-800">{file.name} <button onClick={() => setApprovalFiles((all) => all.filter((_, i) => i !== index))}><X className="inline h-3" /></button></span>)}</div><label className="mt-5 block font-black">Email / Approval Note<textarea value={approvalNote} onChange={(e) => setApprovalNote(e.target.value)} className="form-input mt-2 min-h-32 py-3" /></label></div>}
    </div><footer className="flex shrink-0 justify-end gap-3 border-t border-teal-100 bg-white px-6 py-4"><button onClick={onClose} className="rounded-xl border border-slate-200 px-5 py-3 font-black">Cancel</button><button disabled={saving} onClick={save} className="rounded-xl bg-teal-700 px-6 py-3 font-black text-white disabled:opacity-50">{saving ? 'Saving...' : 'Save And Continue'}</button></footer>
  </section></div>, document.body);
}

function ServiceMultiSelect({ value, onChange }) {
  const [open, setOpen] = useState(false); const [query, setQuery] = useState(''); const filtered = SERVICE_MASTER.filter((item) => item.includes(query.toUpperCase()));
  return <div className="relative min-w-[360px]"><button type="button" onClick={() => setOpen(!open)} className="flex min-h-12 w-full items-center justify-between rounded-xl border border-slate-200 bg-white px-4 text-left"><span className="flex gap-1">{value.slice(0, 2).map((item) => <span key={item} className="max-w-36 truncate rounded-full bg-teal-100 px-2 py-1 text-xs font-bold text-teal-900">{item}</span>)}{value.length > 2 && <span className="rounded-full bg-cyan-100 px-2 py-1 text-xs font-bold">+{value.length - 2} more</span>}{!value.length && <span className="text-slate-400">Select services</span>}</span><ChevronDown className="h-4" /></button>{open && <div className="absolute z-[230] mt-2 w-full rounded-2xl border border-teal-100 bg-white p-3 shadow-2xl"><div className="flex gap-2"><input autoFocus value={query} onChange={(e) => setQuery(e.target.value)} className="form-input" placeholder="Search services" /><button onClick={() => onChange([])} className="whitespace-nowrap text-xs font-black text-red-600">Clear All</button></div><div className="mt-2 max-h-64 overflow-y-auto">{filtered.map((item) => { const selected = value.includes(item); return <label key={item} className={`flex cursor-pointer gap-3 rounded-lg p-3 text-sm font-bold ${selected ? 'bg-teal-50 text-teal-900' : 'hover:bg-slate-50'}`}><input type="checkbox" checked={selected} onChange={() => onChange(selected ? value.filter((entry) => entry !== item) : [...value, item])} />{item}</label>; })}</div></div>}</div>;
}

export function ClientDataProcessing() {
  const { clientKey, annualYear } = useParams(); const navigate = useNavigate(); const [state, setState] = useState('checking');
  useEffect(() => { apiService.clients.getAnnualAccess(clientKey, annualYear).then(() => setState('ready')).catch(() => { setState('locked'); navigate(`/sales/client-annual-returns/${encodeURIComponent(clientKey)}`, { replace: true }); }); }, [clientKey, annualYear]);
  return <DashboardShell currentUser={userFromStorage()} onLogout={() => navigate('/')}><main className="p-7"><button onClick={() => navigate(`/sales/client-annual-returns/${encodeURIComponent(clientKey)}`)} className="rounded-xl border border-teal-200 bg-white px-4 py-3 font-black text-teal-800"><ArrowLeft className="mr-2 inline h-4" />Annual Return History</button><section className="mx-auto mt-6 max-w-5xl rounded-3xl border border-teal-100 bg-white p-8"><h1 className="text-3xl font-black">Annual Return {annualYear}</h1><p className="mt-3 font-semibold text-slate-500">{state === 'ready' ? 'PO access verified. Annual-year processing is unlocked.' : 'Verifying PO access…'}</p></section></main></DashboardShell>;
}
